# Pre-commit configuration file.
# see https://pre-commit.com for more information
# see https://pre-commit.com/hooks.html for more hooks

repos:
  # Out of the box hooks for pre-commit ()
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=5000"]

  # Hook to auto-format non python files (i.a. md, yaml, xml, json)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=79, --ignore-unknown]

  # Hooks: clang-format (formatter), cpplint, cppcheck (static checkers)
  - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
      - id: clang-format
        args: [--style=Google]
      - id: cpplint
      - id: cppcheck
        args: [--inline-suppr]

  # Hook to lint CMake configuration
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: master
    hooks:
      - id: cmakelint
